// tools/franchise-smoke.mjs — the browser-level proof for the Franchise prestige (plan §3.11).
//
// WHY THIS EXISTS. Unit tests can prove that openFranchise() produces the right object and that the
// save boundary accepts it. They cannot prove that the RUNNING GAME survives the reset: that the
// live snapshot really is the shape the partition describes (it is assembled by five separate
// wrappers), that G.restore rebuilds a café out of it, and that the pets, followers and rating the
// player was promised are still there afterwards. This drives the real bundle in a real browser and
// asserts exactly that, then diffs a second snapshot/restore cycle to prove the new state is stable.
//
// Usage:  node tools/franchise-smoke.mjs [--keep]
//   --keep  leave the server up and the build in place for manual inspection
// Exit code 0 = every assertion held.
//
// It builds to dist-franchise/ (never dist/, which several agents share) through a temporary entry
// that loads src/main.js and then installs the bridge exactly as the main.js wiring will:
//
//     const franchise = createFranchiseBridge(G);            // after createGame/G.restore
//     franchise.refresh();                                   // beside goldenPaw.refresh()
//     franchise.update();                                    // in frame(), beside goldenPaw.update
//
// Every temporary file, and the build directory, are deleted on the way out.

import { execSync } from 'node:child_process';
import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { chromium } from 'playwright';
// The evidence a ★5 rating is made of comes from the simulation itself, not from a list retyped
// here: the save boundary re-derives the rating from this evidence on every load, so a staged café
// that is not genuinely ★5 would be demoted on restore and this smoke would be testing a fiction.
import { PAW_PET_KEYS } from '../src/sim/pawRating.js';
import { PET_BESTIE_VISITS } from '../src/sim/petBook.js';

const KEEP = process.argv.includes('--keep');
const ROOT = process.cwd();
const OUT = path.join(ROOT, 'dist-franchise');
const ENTRY = path.join(ROOT, 'franchise-smoke-entry.js');
const PAGE = path.join(ROOT, 'franchise-smoke.html');
const CONFIG = path.join(ROOT, 'vite.franchise-smoke.config.js');
const PORT = 4179;
const types = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.png': 'image/png', '.json': 'application/json' };
const W = ms => new Promise(r => setTimeout(r, ms));

const results = [];
const check = (name, pass, detail = '') => {
  results.push({ name, pass: !!pass, detail });
  console.log(`  ${pass ? 'PASS' : 'FAIL'}  ${name}${detail ? `  — ${detail}` : ''}`);
};

function writeTempSources() {
  const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8')
    .replace('./src/main.js', './franchise-smoke-entry.js');
  fs.writeFileSync(PAGE, html);
  fs.writeFileSync(ENTRY, `// generated by tools/franchise-smoke.mjs — deleted when it finishes
import './src/main.js';
import { createFranchiseBridge } from './src/systems/franchise.js';
const install = () => {
  const G = window.__game;
  if (!G) { setTimeout(install, 30); return; }
  // main.js constructs, refreshes and steps the real bridge (Batch 5 wiring) and exposes it as
  // window.__franchise. Installing a second one attached a second offer row and split lastResult
  // between two objects; use the real one and fall back to a private install only if it is absent.
  if (!window.__franchise) {
    const bridge = createFranchiseBridge(G);
    bridge.refresh();
    window.__franchise = bridge;
    const step = () => { bridge.update(); requestAnimationFrame(step); };
    requestAnimationFrame(step);
  }
};
install();
`);
  fs.writeFileSync(CONFIG, `import { defineConfig } from 'vite';
export default defineConfig({
  base: './',
  build: {
    target: 'es2020', modulePreload: false, assetsInlineLimit: 0,
    outDir: 'dist-franchise', emptyOutDir: true,
    rollupOptions: {
      input: 'franchise-smoke.html',
      output: { manualChunks(id) { if (id.includes('node_modules/three/')) return 'three'; } },
    },
  },
});
`);
}

function cleanup() {
  for (const file of [ENTRY, PAGE, CONFIG]) { try { fs.rmSync(file, { force: true }); } catch (_) {} }
  if (!KEEP) { try { fs.rmSync(OUT, { recursive: true, force: true }); } catch (_) {} }
}

writeTempSources();
try {
  execSync(`npx vite build --config ${JSON.stringify(CONFIG)}`, { stdio: 'inherit' });
} catch (err) {
  cleanup();
  console.error('build failed');
  process.exit(1);
}

const srv = http.createServer((req, res) => {
  let p = path.join(OUT, decodeURIComponent(req.url.split('?')[0]));
  if (p.endsWith(path.sep) || !path.extname(p)) p = path.join(OUT, 'franchise-smoke.html');
  fs.readFile(p, (e, b) => {
    if (e) { res.writeHead(404); res.end(); return; }
    res.writeHead(200, { 'content-type': types[path.extname(p)] || 'application/octet-stream' });
    res.end(b);
  });
}).listen(PORT);

const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 414, height: 896 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true });
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', e => errors.push(String(e.message || e)));
await page.goto(`http://localhost:${PORT}/franchise-smoke.html`, { waitUntil: 'load' });
await page.waitForFunction(() => !!window.__game && !!window.__franchise, null, { timeout: 20000 });
await W(600);

// ---- 1. force a ★5, Golden-Paw café and settle the shift ---------------------------------------
const staged = await page.evaluate(([petKeys, bestieVisits]) => {
  const G = window.__game;
  // A café worth losing: coins, builds, staff, stars, upgrades — plus a rating record that is
  // genuinely ★5 by the boundary's own arithmetic (120+ served, every pet photographed, three
  // Perfects, a Bestie, 16+ discovered, a gold cup, 2000+ followers). Written straight onto the
  // live G, the way the game itself does.
  G.coins = 12_345;
  G.up.income = 3; G.up.speed = 2; G.up.carry = 1;
  G.staff.runner = 2; G.staff.cashier = 1;
  G.staffLevels.runner.speed = 2; G.machineLevels.oven = 2;
  for (const id of ['z_seats1', 'z_oven2', 'z_register2', 'z_coffee']) G.world.built.add(id);
  for (const st of G.world.stations.values()) st.active = !st.builtBy || G.world.built.has(st.builtBy);
  G.stars.oven1 = 3;
  G.stats.served = 5000;
  G.meta.followers = 3400;
  G.meta.goldenPaw = true;
  G.meta.pawBest = 5;
  G.meta.completedDays = 60;
  // The boundary clamps completedDays to the days actually reached, and clamps the career history
  // and the weekly cups with it -- and ★4 needs a gold cup. A day-1 café claiming 60 settled shifts
  // is demoted to ★3 on the first load, which would have made every "the rating survives" assertion
  // below meaningless. So the calendar says day 61 too.
  G.dayState.day = 61;
  G.meta.petBook = {}; G.meta.album = {}; G.meta.petFriendship = {};
  for (let i = 0; i < petKeys.length; i++) {
    const key = petKeys[i];
    G.meta.petBook[key] = 1;
    G.meta.album[key] = { shots: 3, best: i < 3 ? 2 : 1, poseId: null, accessoryId: null };
    G.meta.petFriendship[key] = bestieVisits + 2;
  }
  G.meta.equipped = { [petKeys[0]]: 'acc_bow' };
  G.meta.residents = [petKeys[0]];
  G.meta.career.trophies = { bronze: 0, silver: 0, gold: 1 };
  G.meta.career.weeklyCups = { 8: { tier: 'gold', points: 24, reward: 0 } };
  const window7 = [];
  for (let d = 54; d <= 60; d++) window7.push({ day: d, missed: 0 });
  G.meta.pawSeatWindow = { days: window7, best: 0 };
  // End the shift the way the clock does, so the day summary opens through the real code path.
  G.dayState.t = 239.6;
  for (let i = 0; i < 40 && !G.dayState._ended; i++) G.update(0.05);
  for (let i = 0; i < 20; i++) G.update(0.02);

  // BASELINE: an ordinary snapshot -> restore -> snapshot on the UNfranchised café. Whatever drifts
  // here drifts on every save in the game and is not this feature's doing; the same comparison runs
  // again after the reset, and the two must agree.
  const strip = save => { const c = JSON.parse(JSON.stringify(save)); if (c.intro) delete c.intro.target; return JSON.stringify(c); };
  // The FIRST restore canonicalises whatever this harness forged onto G (dropped builds with unmet
  // dependencies, a clamped career, a generated keepsake), so the fixed point is measured from the
  // second cycle onward -- exactly the comparison the post-franchise check makes, since the state
  // it starts from has already been through this one.
  const baseRestored = G.restore(JSON.parse(JSON.stringify(G.snapshot())));
  const baseA = G.snapshot();
  const baseAText = strip(baseA);
  G.restore(JSON.parse(JSON.stringify(baseA)));
  const baseB = G.snapshot();
  const baseBText = strip(baseB);
  const rawStable = JSON.stringify(baseA) === JSON.stringify(baseB);
  const baseDrift = [];
  for (const k of new Set([...Object.keys(baseA), ...Object.keys(baseB)])) {
    if (JSON.stringify(baseA[k]) !== JSON.stringify(baseB[k])) baseDrift.push(k);
  }

  const before = G.snapshot();
  return {
    ended: !!G.dayState._ended,
    summary: !!document.querySelector('.sheet-root .card'),
    baseline: { restored: baseRestored, stable: baseAText === baseBText, rawStable, drift: baseDrift },
    before: JSON.parse(JSON.stringify({
      coins: before.coins,
      builds: before.builds.a1.length,
      staff: { ...before.staff },
      stars: { ...before.stars },
      upgrades: { ...before.upgrades },
      machineLevels: { ...before.machineLevels },
      petBook: before.meta.petBook,
      album: before.meta.album,
      equipped: before.meta.equipped,
      followers: before.meta.followers,
      residents: before.meta.residents,
      pawBest: before.meta.pawBest,
      goldenPaw: before.meta.goldenPaw,
      franchise: before.meta.franchise,
    })),
  };
}, [PAW_PET_KEYS, PET_BESTIE_VISITS]);
check('the shift settles and the day summary opens', staged.ended && staged.summary,
  `ended=${staged.ended} summary=${staged.summary}`);
check('BASELINE: an ordinary snapshot -> restore -> snapshot is stable before any franchise',
  staged.baseline.restored !== false && staged.baseline.stable,
  staged.baseline.rawStable
    ? 'byte-identical'
    : `drift in ${JSON.stringify(staged.baseline.drift)} (intro.target is a per-frame field the save `
      + 'boundary drops and systems/intro.js recomputes; anything else here is pre-existing and '
      + 'unrelated to the franchise)');

// ---- 2. the offer appears in the summary, and only there ---------------------------------------
// The summary card animates in from transform:scale(.92) over 0.22s; measuring a tap target before
// that settles measures the animation, not the layout.
await W(900);
const offer = await page.evaluate(() => {
  const row = document.querySelector('.franchise-offer');
  const btn = row && row.querySelector('.franchise-offer-btn');
  const rect = btn && btn.getBoundingClientRect();
  return { row: !!row, tap: rect ? Math.round(rect.height) : 0 };
});
check('the offer row is attached to the day summary', offer.row);
check('its button meets the 44px tap minimum', offer.tap >= 44, `${offer.tap}px`);

const sheetState = await page.evaluate(() => {
  document.querySelector('.franchise-offer-btn').click();
  const root = document.querySelector('.fr-root');
  const card = root && root.querySelector('.fr-card');
  const body = root && root.querySelector('.fr-body');
  const accept = root && root.querySelector('.fr-accept');
  const decline = root && root.querySelector('.fr-decline');
  return {
    open: !!root && !root.classList.contains('hidden'),
    scrolls: !!body && body.scrollHeight >= body.clientHeight,
    insideViewport: card ? card.getBoundingClientRect().bottom <= window.innerHeight + 1 : false,
    acceptTap: accept ? Math.round(accept.getBoundingClientRect().height) : 0,
    declineTap: decline ? Math.round(decline.getBoundingClientRect().height) : 0,
    armedLabelBefore: accept ? accept.textContent : '',
  };
});
check('the offer sheet opens on tap', sheetState.open);
check('the sheet fits the viewport and scrolls internally', sheetState.insideViewport && sheetState.scrolls);
check('both decisions are >= 44px', sheetState.acceptTap >= 44 && sheetState.declineTap >= 44,
  `accept=${sheetState.acceptTap} decline=${sheetState.declineTap}`);

// ---- 3. one tap arms, the second commits --------------------------------------------------------
const armed = await page.evaluate(() => {
  const accept = document.querySelector('.fr-accept');
  accept.click();
  return { armed: accept.classList.contains('is-armed'), coins: window.__game.coins };
});
check('the first tap only arms the reset — nothing has changed yet', armed.armed && armed.coins === 12_345,
  `coins still ${armed.coins}`);

const after = await page.evaluate(async () => {
  document.querySelector('.fr-accept').click();
  await new Promise(r => setTimeout(r, 120));
  const G = window.__game;
  const snap = G.snapshot();
  const seen = {
    coins: snap.coins,
    builds: snap.builds.a1.length,
    staff: { ...snap.staff },
    stars: { ...snap.stars },
    upgrades: { ...snap.upgrades },
    machineLevels: { ...snap.machineLevels },
    petBook: snap.meta.petBook,
    album: snap.meta.album,
    equipped: snap.meta.equipped,
    followers: snap.meta.followers,
    residents: snap.meta.residents,
    pawBest: snap.meta.pawBest,
    goldenPaw: snap.meta.goldenPaw,
    franchise: snap.meta.franchise,
  };
  // Snapshot -> restore -> snapshot: the new state must be a fixed point of the save boundary.
  // Same comparison as the baseline above, including the same intro.target exclusion, so the two
  // measure exactly the same thing.
  const strip = save => { const c = JSON.parse(JSON.stringify(save)); if (c.intro) delete c.intro.target; return JSON.stringify(c); };
  const first = strip(snap);
  const restored = G.restore(JSON.parse(JSON.stringify(snap)));
  const second = strip(G.snapshot());
  const result = window.__franchise.lastResult;
  return {
    seen: JSON.parse(JSON.stringify(seen)),
    liveBuilt: G.world.built.size,
    liveStaff: G.staffList.length,
    sheetClosed: document.querySelector('.fr-root').classList.contains('hidden'),
    restored,
    stable: first === second,
    firstLen: first.length,
    drift: first === second ? null : (() => {
      const a = JSON.parse(first), b = JSON.parse(second), out = [];
      for (const k of new Set([...Object.keys(a), ...Object.keys(b)])) {
        if (JSON.stringify(a[k]) !== JSON.stringify(b[k])) out.push(k);
      }
      return out;
    })(),
    unknownFields: result ? result.unknown : ['<no result>'],
    keptFields: result ? result.kept.length : 0,
    resetFields: result ? result.reset.length : 0,
  };
});

const before = staged.before, seen = after.seen;
const same = (a, b) => JSON.stringify(a) === JSON.stringify(b);
check('the sheet closes on commit', after.sheetClosed);
check('the partition names every field of the REAL runtime snapshot',
  Array.isArray(after.unknownFields) && after.unknownFields.length === 0,
  `unknown: ${JSON.stringify(after.unknownFields)}`);
check('coins reset', seen.coins === 0, `${before.coins} -> ${seen.coins}`);
check('builds reset to the opening café', seen.builds === 0 && after.liveBuilt === 0,
  `${before.builds} zones -> ${seen.builds} (live world ${after.liveBuilt})`);
check('staff reset', Object.values(seen.staff).every(n => n === 0) && after.liveStaff === 0,
  `${JSON.stringify(before.staff)} -> ${JSON.stringify(seen.staff)}, ${after.liveStaff} on the floor`);
check('station stars reset', Object.keys(seen.stars).length === 0,
  `${JSON.stringify(before.stars)} -> ${JSON.stringify(seen.stars)}`);
check('player upgrades and machines reset',
  seen.upgrades.income === 0 && seen.upgrades.speed === 0 && seen.machineLevels.oven === 0,
  `${JSON.stringify(before.upgrades)} -> ${JSON.stringify(seen.upgrades)}`);
check('petBook kept', same(before.petBook, seen.petBook));
check('album kept', same(before.album, seen.album));
check('equipped accessories kept', same(before.equipped, seen.equipped));
check('followers kept', before.followers === seen.followers, `${before.followers} -> ${seen.followers}`);
check('residents kept', same(before.residents, seen.residents), JSON.stringify(seen.residents));
check('pawBest kept', before.pawBest === seen.pawBest, `${before.pawBest} -> ${seen.pawBest}`);
check('goldenPaw kept', seen.goldenPaw === true);
check('the franchise level advanced and its multiplier is derived',
  seen.franchise && seen.franchise.level === 1 && seen.franchise.multiplier === 1.08,
  JSON.stringify(seen.franchise));
check('snapshot -> restore of the new state changes nothing',
  after.restored !== false && after.stable,
  after.stable ? `${after.firstLen} bytes, identical` : `drift in: ${JSON.stringify(after.drift)}`);
check('no page errors', errors.length === 0, errors.slice(0, 3).join(' | '));

const failed = results.filter(r => !r.pass);
console.log(`\n${results.length - failed.length}/${results.length} checks passed.`);
for (const f of failed) console.log(`  FAILED: ${f.name} — ${f.detail}`);

await browser.close();
if (!KEEP) srv.close(); else console.log(`server still on http://localhost:${PORT}/franchise-smoke.html (--keep)`);
cleanup();
process.exit(failed.length ? 1 : 0);
