// Live adapter for sim/ledger.js. It observes the existing economy without changing prices,
// rewards, penalties, timing or ownership. Explicit checkpoint reasons classify purchases and
// collections; unclassified wallet decreases are service/waste deductions and increases are
// bonuses. Sales are observed separately because they accrue into register piles, not the wallet.
import { createLedger } from '../sim/ledger.js';
import { subscribeWorld } from '../sim/events.js';

// Every checkpoint reason that systems/*.js marks straight after a successful purchase has to be
// listed here. A missing reason is not cosmetic: the coins still leave the wallet, classify()
// never runs, the decrease falls through to 'wallet:service-or-waste', and the shift ledger stops
// reconciling -- which is exactly what the headless bot gates on.
const SPEND_REASONS = new Set([
  'renovation', 'player-upgrade', 'staff-hire', 'worker-upgrade', 'machine-upgrade', 'station-star',
  'decor-buy',
  'build-payment', 'build-payment-stop', 'build-complete',
]);

function paidForZone(world, zone) {
  if (world.built && world.built.has(zone.id)) return Math.max(0, zone.price | 0);
  return Math.max(0, world.partial && world.partial[zone.id] | 0);
}

export function installEconomicLedger(G) {
  if (!G || typeof G !== 'object' || !G.world) return { destroy() {}, report:() => null };
  if (G.economicLedger && typeof G.economicLedger.report === 'function') return G.economicLedger;

  const world = G.world;
  const ledger = createLedger(null, { day:G.dayState && G.dayState.day || 1, openingWallet:G.coins || 0 });
  let wallet = Math.max(0, Math.round(Number(G.coins) || 0));
  let armed = true;
  let restoring = false;
  let restoreLedger = null;
  let pending = [];

  const coinDescriptor = Object.getOwnPropertyDescriptor(G, 'coins');
  Object.defineProperty(G, 'coins', {
    configurable: true,
    enumerable: true,
    get() { return wallet; },
    set(value) {
      const next = Math.max(0, Math.round(Number(value) || 0));
      const delta = next - wallet;
      wallet = next;
      if (!armed || !delta) return;
      // Transaction IDs belong to sim/ledger.js, whose monotonic counter survives save/restore.
      // Do not invent a second runtime counter here or a reload could collide with an older ID.
      pending.push({ delta, amount:Math.abs(delta), type:null, category:null, meta:null });
    },
  });

  function classify(kind, category, predicate = null, meta = null) {
    const sign = kind === 'collection' || kind === 'bonus' ? 1 : -1;
    for (let i = pending.length - 1; i >= 0; i--) {
      const p = pending[i];
      if (p.type || Math.sign(p.delta) !== sign || (predicate && !predicate(p))) continue;
      p.type = kind; p.category = category; p.meta = meta;
      return p;
    }
    return null;
  }

  function classifyBuildSpend(beforePaid) {
    for (const zone of world.area && world.area.zones || []) {
      const before = beforePaid.get(zone.id) || 0;
      const after = paidForZone(world, zone);
      const spent = Math.max(0, after - before);
      if (!spent) continue;
      let remaining = spent;
      for (const p of pending) {
        if (p.type || p.delta >= 0 || remaining <= 0) continue;
        if (p.amount <= remaining) {
          p.type = 'spend'; p.category = `build:${zone.id}`; p.meta = { zoneId:zone.id };
          remaining -= p.amount;
        }
      }
    }
  }

  function flushPending() {
    if (!pending.length) return;
    for (const p of pending) {
      const type = p.type || (p.delta > 0 ? 'bonus' : 'deduction');
      const category = p.category || (p.delta > 0 ? 'wallet:bonus' : 'wallet:service-or-waste');
      ledger.record(type, category, p.amount, { meta:p.meta });
    }
    pending = [];
  }

  function syncDayBoundary() {
    const liveDay = Math.max(1, G.dayState && G.dayState.day | 0 || 1);
    if (liveDay === ledger.day) return;
    // Finish the previous shift before opening the new baseline. This also captures a fee/bonus
    // generated by an outer runtime wrapper after the economic adapter's preceding update.
    flushPending();
    ledger.reset(liveDay, G.coins);
  }

  const unsubscribeSale = subscribeWorld(world, event => {
    if (!event || event.type !== 'pay' || !armed) return;
    const customer = (G.customers || []).find(c => c && c.id === event.id);
    const order = customer && Array.isArray(customer.order) ? customer.order.filter(Boolean) : [];
    ledger.record(
      'sale',
      `service:${order.length ? order.join('+') : 'unknown'}`,
      event.amount,
      { meta:{ customerId:event.id, checkoutId:event.checkoutId || null } },
    );
  }, 80);

  const baseCheckpoint = G.requestCheckpoint;
  if (typeof baseCheckpoint === 'function') {
    G.requestCheckpoint = reason => {
      if (reason === 'cash-collection') classify('collection', 'register:cash');
      else if (SPEND_REASONS.has(reason)) classify('spend', `purchase:${reason}`);
      return baseCheckpoint(reason);
    };
  }

  const baseUpdate = G.update;
  if (typeof baseUpdate === 'function') {
    G.update = function economicLedgerUpdate(dt) {
      syncDayBoundary();
      const beforePaid = new Map();
      for (const zone of world.area && world.area.zones || []) beforePaid.set(zone.id, paidForZone(world, zone));
      const result = baseUpdate(dt);
      classifyBuildSpend(beforePaid);
      flushPending();
      return result;
    };
  }

  const baseSnapshot = G.snapshot;
  if (typeof baseSnapshot === 'function') {
    G.snapshot = () => {
      syncDayBoundary();
      flushPending();
      const save = baseSnapshot();
      save.ledger = restoring && restoreLedger ? restoreLedger : ledger.snapshot();
      return save;
    };
  }

  const baseRestore = G.restore;
  if (typeof baseRestore === 'function') {
    G.restore = save => {
      armed = false; restoring = true; restoreLedger = save && save.ledger || null; pending = [];
      const ok = baseRestore(save);
      if (ok !== false) ledger.restore(restoreLedger, G.coins, G.dayState && G.dayState.day || 1);
      wallet = Math.max(0, Math.round(Number(G.coins) || 0));
      pending = []; restoring = false; restoreLedger = null; armed = true;
      return ok;
    };
  }

  const api = {
    ledger,
    flush:flushPending,
    report() { syncDayBoundary(); flushPending(); return ledger.report(G.coins); },
    resetForDay(day = G.dayState && G.dayState.day, opening = G.coins) { flushPending(); ledger.reset(day, opening); },
    destroy() {
      flushPending(); unsubscribeSale();
      if (typeof baseCheckpoint === 'function' && G.requestCheckpoint !== baseCheckpoint) G.requestCheckpoint = baseCheckpoint;
      if (typeof baseUpdate === 'function' && G.update !== baseUpdate) G.update = baseUpdate;
      if (typeof baseSnapshot === 'function' && G.snapshot !== baseSnapshot) G.snapshot = baseSnapshot;
      if (typeof baseRestore === 'function' && G.restore !== baseRestore) G.restore = baseRestore;
      Object.defineProperty(G, 'coins', coinDescriptor || { configurable:true, enumerable:true, writable:true, value:wallet });
      G.coins = wallet;
    },
  };
  G.economicLedger = api;
  return api;
}
